#' Generate an IOP Qualification Report
#'
#' Creates a report in either PDF or HTML format based on specified settings.
#'  The function relies on `pdfcrop` if a PDF report is required (unless
#'  `html_report` is TRUE), and the settings for the report are read from a
#'  YAML file. The function performs checks to ensure all directories and files
#'  are in place before proceeding with the report generation. If required
#'  checks fail, it will stop and provide an informative error message.
#'
#' @param settings_file The name of the settings file (in YAML format) used to
#'   generate the report. It should have a "*.yaml" extension.
#' @param settings_directory The full path to the directory where the settings
#'  file is stored. This directory should exist and be readable.
#' @param input_directory The full path to the directory where the RMarkdown
#'  file for the report is stored. This directory should exist and be readable.
#' @param test_outputs_directory The full path to the directory where the test
#'  outputs should be stored. This directory either should already exist or will
#'  be created by the function.
#' @param html_report A logical flag indicating whether an HTML report should
#'  be generated instead of a PDF. Defaults to FALSE, meaning a PDF report is
#'   generated by default.
#' @return The function does not return a value but generates a report file in
#'  the specified output format and location.
#' @export
#' @examples
#' \dontrun{
#' iop_create_report(
#'   input_directory = "/path/to/input",
#'   settings_directory = "/path/to/settings",
#'   test_outputs_directory = "/path/to/test/output",
#'   settings_file = "settings.yaml",
#'   html_report = FALSE
#' )
#' }
iop_create_report <- function(input_directory, settings_directory,
                              test_outputs_directory, settings_file,
                              html_report = FALSE) {
  # Check pdfcrop, and subsequently tinytex, is installed:
  if ((system("pdfcrop --version") != 0) && (!html_report)) {
    stop("The application `pdfcrop` couldn't not be found in your system, which
         may mean tinytex is missing or misconfigured. Please run
         iop_help_tex() to perform an automatic repair attempt.\n
         Alternatively, you can generate a HTML report by adding
         `html_report=TRUE` to the `iop_create_report()` function.")
  }

  assert_that(is.character(settings_file), length(settings_file) > 0)
  assert_that(is.character(settings_directory), dir.exists(settings_directory))
  assert_that(is.character(input_directory), dir.exists(input_directory))
  assert_that(
    is.character(test_outputs_directory),
    dir.exists(test_outputs_directory)
  )
  assert_that(is.logical(html_report))

  if (!iop_check_output_dir(
    input_directory, settings_directory,
    test_outputs_directory
  )) {
    stop("The `test_outputs_directory` must point to a folder different of both
         `input_directory` and `settings_directory`. Please create an exclusive
         folder to the output.")
  }
  # Check that Rmd file and inputs file exist:
  if (!file.exists(file.path(settings_directory, settings_file))) {
    if (settings_directory == dirname(settings_file)) {
      settings_file <- basename(settings_file)
    } else {
      stop("Settings file cannot be found")
    }
  }

  assign(x = "settings", value = iop_load_input_file(file.path(
    settings_directory,
    settings_file
  ), tests_output_dir = test_outputs_directory), envir = globalenv())

  if (!file.exists(file.path(input_directory, "report.Rmd"))) {
    stop("Base report Rmd file cannot be found")
  }

  # Creating the outputs directory for the `tools` tests, if it does not exist:
  if (!dir.exists(test_outputs_directory)) {
    dir.create(test_outputs_directory)
  }
  # Delete (any) files in the tests output directory:
  list.files(test_outputs_directory, full.names = TRUE) %>%
    file.remove()

  output_format_selected <- ifelse(html_report, "html_document", "pdf_document")
  output_file_selected <- ifelse(html_report, "report.html", "report.pdf")

  render(
    input = file.path(input_directory, "report.Rmd"),
    output_format = output_format_selected,
    output_dir = input_directory,
    output_file = output_file_selected,
    clean = TRUE
  )
}

#' Custom print function for xtable objects in report
#' @param x An `xtable` object, or an object that can be coerced to `xtable`.
#' If `NULL`, the function returns `NULL`.
#' @param caption The caption to be used for the table when printed. It should
#' be a character string.
#' @param ... Additional arguments passed to `xtable::print.xtable`.
iop_print_xtable <- function(x, caption, ...) {
  assert_that(is.null(x) || inherits(x, "xtable") || (is.data.frame(x) &&
    all(sapply(
      x,
      is.atomic
    ))))
  assert_that(is.character(caption))
  if (is.null(x)) {
    return(NULL)
  }
  x %>%
    iop_color_logical() %>%
    xtable(caption = caption) %>%
    print.xtable(
      hline.after = (-1):nrow(x),
      type = ifelse(is_html_output(), "html", "latex"),
      sanitize.text.function = iop_custom_sanitize, ...
    )
}

#' Color false logical values as 'red'
#' @param d (data frame)
iop_color_logical <- function(d) {
  if (is.null(d)) {
    return(NULL)
  }
  mutate(
    d,
    across(
      where(is.logical),
      ~ ifelse(.x, .x, str_c("\\textcolor{red!100}{", .x, "}"))
    )
  )
}

#' Sanitize function which does not sanitize custom coloring of logical values
#' @param char (character length 1) character string to "sanitize"
#' @param type (character length 1) type of sanitization to apply,
#' defaults to "latex"
iop_custom_sanitize <- function(char, type = "latex") {
  ifelse(
    str_detect(char, "\\\\textcolor.*FALSE"),
    char,
    sanitize(char, type = type)
  )
}

#' Help function to make tinytex available
#' @export
iop_help_tex <- function() {
  install.packages("tinytex")
  tinytex::tlmgr_install("pdfcrop")
}

#' Add statement to final row of multi-page table
iop_custom_add_row <- function() {
  list(pos = list(0), command = paste0(
    "\\hline \n",
    "\\endhead \n",
    "\\hline \n",
    "{\\footnotesize Continued on next page} \n",
    "\\endfoot \n",
    "\\endlastfoot \n"
  ))
}
